name: mandarinvpn
description: VPN application

version: 2.15.11+78

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <=1.22.6"

dependencies:
  adapty_flutter: ^2.9.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  device_apps: ^2.2.0
  device_info: ^2.0.3
  devicelocale: ^0.7.0
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_locales: ^2.0.0
  flutter_mailer: ^2.1.2
  flutter_svg: ^1.0.1
  flutter_vpn: ^0.12.0
  http: ^0.13.5
  package_info: ^2.0.2
  provider: ^6.0.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.2
  toast: ^0.3.0
  rate_my_app: ^1.1.3
  progress_state_button: ^1.0.4
  stack_appodeal_flutter: ^3.0.1
  appmetrica_push_plugin: ^0.3.0
  appmetrica_plugin: ^1.4.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  flutter_email_sender: ^6.0.2
  device_region: ^1.3.0
  firebase_remote_config: ^4.3.8
  vibration: ^1.8.4

  # ip_geolocation: ^1.0.0
  # public_ip_address: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Rubic
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

  assets:
    - assets/images/vectors/
    - assets/images/rasters/
    - assets/images/rasters/flags/
    - assets/locales/
    - assets/images/vectors/coutry_map/
